# Generated by Django 4.0.5 on 2022-06-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmt_app', '0003_tag_user_project_description_alter_project_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Group Name', max_length=256),
        ),
    ]
