# Generated by Django 4.0.5 on 2022-06-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmt_app', '0004_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Team Name', max_length=256)),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(blank=True, to='gmt_app.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gmt_app.team'),
        ),
    ]
