# Generated by Django 4.0.5 on 2022-06-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmt_app', '0009_alter_project_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.URLField(blank=True, verbose_name='user profile address'),
        ),
    ]
