# Generated by Django 4.0.5 on 2022-06-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmt_app', '0011_alter_project_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pub_date'),
        ),
    ]
