# Generated by Django 4.0.5 on 2022-06-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmt_app', '0019_bugtag_alter_project_pub_date_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='issues',
            field=models.ManyToManyField(blank=True, to='gmt_app.issue'),
        ),
    ]
