# Generated by Django 4.0.5 on 2022-06-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmt_app', '0020_project_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.CharField(blank=True, choices=[('1', 'enhancment'), ('2', 'minor'), ('3', 'major'), ('4', 'critical'), ('5', 'blocker')], max_length=15, null=True),
        ),
    ]
