# Generated by Django 4.0.5 on 2022-06-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmt_app', '0021_alter_issue_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='issues',
        ),
        migrations.AddField(
            model_name='project',
            name='issues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmt_app.issue'),
        ),
    ]
