# Generated by Django 4.0.5 on 2022-06-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmt_app', '0022_remove_project_issues_project_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='issues',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmt_app.issue'),
        ),
    ]
