# Generated by Django 4.0.5 on 2022-06-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmt_app', '0024_remove_project_issues_issue_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
