# Generated by Django 4.0.5 on 2022-07-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmt_app', '0034_alter_issue_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='githubURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
